using System;

namespace POS.Domain.Types;

/// <summary>
/// Unidades de medida oficiales de la DGII (códigos 1 al 62).
/// Referencia: Catálogo de Unidades de Medida en esquemas XSD de DGII.
/// </summary>
public enum UnidadMedidaType : int
{
    Barril = 1,
    Bolsa = 2,
    Bote = 3,
    Bulto = 4,
    Botella = 5,
    Caja_Cajon = 6,
    Cajetilla = 7,
    Centimetro = 8,
    Cilindro = 9,
    Conjunto = 10,
    Contenedor = 11,
    Dia = 12,
    Docena = 13,
    Fardo = 14,
    Galones = 15,
    Grado = 16,
    Gramo = 17,
    Granel = 18,
    Hora = 19,
    Huacal = 20,
    Kilogramo = 21,
    KilovatioHora = 22,
    Libra = 23,
    Litro = 24,
    Lote = 25,
    Metro = 26,
    Metro_Cuadrado = 27,
    Metro_Cubico = 28,
    MMBTU = 29,
    Minuto = 30,
    Paquete = 31,
    Par = 32,
    Pie = 33,
    Pieza = 34,
    Rollo = 35,
    Sobre = 36,
    Segundo = 37,
    Tanque = 38,
    Tonelada = 39,
    Tubo = 40,
    Yarda = 41,
    Yarda_Cuadrada = 42,
    Unidad = 43,
    Elemento = 44,
    Millar = 45,
    Saco = 46,
    Lata = 47,
    Display = 48,
    Bidon = 49,
    Racion = 50,
    Quintal = 51,
    ToneladasRegistroBruto = 52,
    Pie_Cuadrado = 53,
    Pasajero = 54,
    Pulgadas = 55,
    ParqueoBarcosMuelle = 56,
    Bandeja = 57,
    Hectarea = 58,
    Mililitro = 59,
    Miligramo = 60,
    Onzas = 61,
    OnzasTroy = 62
}

public static class UnidadMedidaFormatter
{
    public static string GetDescripcion(UnidadMedidaType unidad) => unidad switch
    {
        UnidadMedidaType.Barril => "BARR - Barril",
        UnidadMedidaType.Bolsa => "BOL - Bolsa",
        UnidadMedidaType.Bote => "BOT - Bote",
        UnidadMedidaType.Bulto => "BULTO - Bultos",
        UnidadMedidaType.Botella => "BOTELLA - Botella",
        UnidadMedidaType.Caja_Cajon => "CAJ - Caja/Cajón",
        UnidadMedidaType.Cajetilla => "CAJETILLA - Cajetilla",
        UnidadMedidaType.Centimetro => "CM - Centímetro",
        UnidadMedidaType.Cilindro => "CIL - Cilindro",
        UnidadMedidaType.Conjunto => "CONJ - Conjunto",
        UnidadMedidaType.Contenedor => "CONT - Contenedor",
        UnidadMedidaType.Dia => "DÍA - Día",
        UnidadMedidaType.Docena => "DOC - Docena",
        UnidadMedidaType.Fardo => "FARD - Fardo",
        UnidadMedidaType.Galones => "GL - Galones",
        UnidadMedidaType.Grado => "GRAD - Grado",
        UnidadMedidaType.Gramo => "GR - Gramo",
        UnidadMedidaType.Granel => "GRAN - Granel",
        UnidadMedidaType.Hora => "HOR - Hora",
        UnidadMedidaType.Huacal => "HUAC - Huacal",
        UnidadMedidaType.Kilogramo => "KG - Kilogramo",
        UnidadMedidaType.KilovatioHora => "kWh - Kilovatio Hora",
        UnidadMedidaType.Libra => "LB - Libra",
        UnidadMedidaType.Litro => "LITRO - Litro",
        UnidadMedidaType.Lote => "LOT - Lote",
        UnidadMedidaType.Metro => "M - Metro",
        UnidadMedidaType.Metro_Cuadrado => "M2 - Metro Cuadrado",
        UnidadMedidaType.Metro_Cubico => "M3 - Metro Cúbico",
        UnidadMedidaType.MMBTU => "MMBTU - Millones de Unidades Térmicas",
        UnidadMedidaType.Minuto => "MIN - Minuto",
        UnidadMedidaType.Paquete => "PAQ - Paquete",
        UnidadMedidaType.Par => "PAR - Par",
        UnidadMedidaType.Pie => "PIE - Pie",
        UnidadMedidaType.Pieza => "PZA - Pieza",
        UnidadMedidaType.Rollo => "ROL - Rollo",
        UnidadMedidaType.Sobre => "SOBR - Sobre",
        UnidadMedidaType.Segundo => "SEG - Segundo",
        UnidadMedidaType.Tanque => "TANQUE - Tanque",
        UnidadMedidaType.Tonelada => "TONE - Tonelada",
        UnidadMedidaType.Tubo => "TUB - Tubo",
        UnidadMedidaType.Yarda => "YD - Yarda",
        UnidadMedidaType.Yarda_Cuadrada => "YD2 - Yarda cuadrada",
        UnidadMedidaType.Unidad => "UND - Unidad",
        UnidadMedidaType.Elemento => "EA - Elemento",
        UnidadMedidaType.Millar => "MILLAR - Millar",
        UnidadMedidaType.Saco => "SAC - Saco",
        UnidadMedidaType.Lata => "LAT - Lata",
        UnidadMedidaType.Display => "DIS - Display",
        UnidadMedidaType.Bidon => "BID - Bidón",
        UnidadMedidaType.Racion => "RAC - Ración",
        UnidadMedidaType.Quintal => "Q - Quintal",
        UnidadMedidaType.ToneladasRegistroBruto => "GRT - Toneladas de registro bruto",
        UnidadMedidaType.Pie_Cuadrado => "P2 - Pie Cuadrado",
        UnidadMedidaType.Pasajero => "PAX - Pasajero",
        UnidadMedidaType.Pulgadas => "PULG - Pulgadas",
        UnidadMedidaType.ParqueoBarcosMuelle => "STAY - Parqueo Barcos en Muelle",
        UnidadMedidaType.Bandeja => "BDJ - Bandeja",
        UnidadMedidaType.Hectarea => "HA - Hectárea",
        UnidadMedidaType.Mililitro => "ML - Mililitro",
        UnidadMedidaType.Miligramo => "MG - Miligramo",
        UnidadMedidaType.Onzas => "OZ - Onzas",
        UnidadMedidaType.OnzasTroy => "OZT - Onzas Troy",
        _ => throw new ArgumentOutOfRangeException(nameof(unidad))
    };

    public static string GetAbreviatura(UnidadMedidaType unidad) => unidad switch
    {
        UnidadMedidaType.Barril => "BARR",
        UnidadMedidaType.Bolsa => "BOL",
        UnidadMedidaType.Bote => "BOT",
        UnidadMedidaType.Bulto => "BULTO",
        UnidadMedidaType.Botella => "BOTELLA",
        UnidadMedidaType.Caja_Cajon => "CAJ",
        UnidadMedidaType.Cajetilla => "CAJETILLA",
        UnidadMedidaType.Centimetro => "CM",
        UnidadMedidaType.Cilindro => "CIL",
        UnidadMedidaType.Conjunto => "CONJ",
        UnidadMedidaType.Contenedor => "CONT",
        UnidadMedidaType.Dia => "DÍA",
        UnidadMedidaType.Docena => "DOC",
        UnidadMedidaType.Fardo => "FARD",
        UnidadMedidaType.Galones => "GL",
        UnidadMedidaType.Grado => "GRAD",
        UnidadMedidaType.Gramo => "GR",
        UnidadMedidaType.Granel => "GRAN",
        UnidadMedidaType.Hora => "HOR",
        UnidadMedidaType.Huacal => "HUAC",
        UnidadMedidaType.Kilogramo => "KG",
        UnidadMedidaType.KilovatioHora => "kWh",
        UnidadMedidaType.Libra => "LB",
        UnidadMedidaType.Litro => "LITRO",
        UnidadMedidaType.Lote => "LOT",
        UnidadMedidaType.Metro => "M",
        UnidadMedidaType.Metro_Cuadrado => "M2",
        UnidadMedidaType.Metro_Cubico => "M3",
        UnidadMedidaType.MMBTU => "MMBTU",
        UnidadMedidaType.Minuto => "MIN",
        UnidadMedidaType.Paquete => "PAQ",
        UnidadMedidaType.Par => "PAR",
        UnidadMedidaType.Pie => "PIE",
        UnidadMedidaType.Pieza => "PZA",
        UnidadMedidaType.Rollo => "ROL",
        UnidadMedidaType.Sobre => "SOBR",
        UnidadMedidaType.Segundo => "SEG",
        UnidadMedidaType.Tanque => "TANQUE",
        UnidadMedidaType.Tonelada => "TONE",
        UnidadMedidaType.Tubo => "TUB",
        UnidadMedidaType.Yarda => "YD",
        UnidadMedidaType.Yarda_Cuadrada => "YD2",
        UnidadMedidaType.Unidad => "UND",
        UnidadMedidaType.Elemento => "EA",
        UnidadMedidaType.Millar => "MILLAR",
        UnidadMedidaType.Saco => "SAC",
        UnidadMedidaType.Lata => "LAT",
        UnidadMedidaType.Display => "DIS",
        UnidadMedidaType.Bidon => "BID",
        UnidadMedidaType.Racion => "RAC",
        UnidadMedidaType.Quintal => "Q",
        UnidadMedidaType.ToneladasRegistroBruto => "GRT",
        UnidadMedidaType.Pie_Cuadrado => "P2",
        UnidadMedidaType.Pasajero => "PAX",
        UnidadMedidaType.Pulgadas => "PULG",
        UnidadMedidaType.ParqueoBarcosMuelle => "STAY",
        UnidadMedidaType.Bandeja => "BDJ",
        UnidadMedidaType.Hectarea => "HA",
        UnidadMedidaType.Mililitro => "ML",
        UnidadMedidaType.Miligramo => "MG",
        UnidadMedidaType.Onzas => "OZ",
        UnidadMedidaType.OnzasTroy => "OZT",
        _ => throw new ArgumentOutOfRangeException(nameof(unidad))
    };

    public static UnidadMedidaType FromCode(int code)
    {
        if (code < 1 || code > 62)
            throw new ArgumentOutOfRangeException(nameof(code), $"Código de unidad de medida inválido: {code}. Debe estar entre 1 y 62.");
        return (UnidadMedidaType)code;
    }
}
