<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\POS.Domain.Types\POS.Domain.Types.csproj" />
    <ProjectReference Include="..\..\src\POS.Domain\POS.Domain.csproj" />
    <ProjectReference Include="..\..\src\POS.Application\POS.Application.csproj" />
    <ProjectReference Include="..\..\src\POS.Infrastructure\POS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
